//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Nhom7_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongDan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongDan()
        {
            this.QuanHes = new HashSet<QuanHe>();
            this.QuanHes1 = new HashSet<QuanHe>();
            this.SoHoKhaus = new HashSet<SoHoKhau>();
            this.ThanhVienSoHoKhaus = new HashSet<ThanhVienSoHoKhau>();
        }
    
        public string hoTen { get; set; }
        public string ngayThangNamSinh { get; set; }
        public string gioiTinh { get; set; }
        public string cmnd { get; set; }
        public string danToc { get; set; }
        public string tinhTrangHonNhan { get; set; }
        public string noiDangKiKhaiSinh { get; set; }
        public string queQuan { get; set; }
        public string noiThuongTru { get; set; }
        public string trinhDoHocVan { get; set; }
        public string ngheNghiep { get; set; }
        public string luong { get; set; }
        public string soLanKetHon { get; set; }
        public string tamTru { get; set; }
        public string noiCapCMND { get; set; }
        public string ngayCap { get; set; }
        public string quocTich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanHe> QuanHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanHe> QuanHes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoHoKhau> SoHoKhaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhVienSoHoKhau> ThanhVienSoHoKhaus { get; set; }
        public virtual Thue Thue { get; set; }
    }
}
