//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Nhom7_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiCongDanEntities : DbContext
    {
        public QuanLiCongDanEntities()
            : base("name=QuanLiCongDanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CongDan> CongDans { get; set; }
        public virtual DbSet<QuanHe> QuanHes { get; set; }
        public virtual DbSet<SoHoKhau> SoHoKhaus { get; set; }
        public virtual DbSet<ThanhVienSoHoKhau> ThanhVienSoHoKhaus { get; set; }
        public virtual DbSet<Thue> Thues { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
