//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Nhom7_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoHoKhau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoHoKhau()
        {
            this.ThanhVienSoHoKhaus = new HashSet<ThanhVienSoHoKhau>();
        }
    
        public string maSoHoKhau { get; set; }
        public string CMNDChuHo { get; set; }
        public string maKV { get; set; }
        public string xaPhuong { get; set; }
        public string quanHuyen { get; set; }
        public string tinhTP { get; set; }
        public string diaChi { get; set; }
        public string ngayLap { get; set; }
    
        public virtual CongDan CongDan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhVienSoHoKhau> ThanhVienSoHoKhaus { get; set; }
    }
}
