//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Nhom7_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thue
    {
        public string CCCD { get; set; }
        public string LoaiThue { get; set; }
        public Nullable<float> MucThue { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual CongDan CongDan { get; set; }
    }
}
